### ISSUE TITLE
Allow to run only on changed files that are about to be pushed

### ISSUE THREAD

**Issue by gkatsev** [videojs/standard#15]
We often use this project in a pre-push hook. Right now, it'll run the linting on all the javascript files before pushing. This is kind of annoying, especially if you made a change only to non-javascript files (until we start linting markdown files).
We should have an option that will check to see which files have changed or are about to be pushed and then only lint those, if valid files are available, it should not lint anything.
Here's a bash command showcasing what is intended:

``` sh
$ `FILES=$(git diff --name-only --cached $(git rev-parse --abbrev-ref --symbolic-full-name @{u}) | grep .js) [ -n "$FILES" ] && vjsstandard $FILES`
```

The expected command should look something like:

``` sh
$ vjsstandard --git-changed
```

Sidenote: this should support windows.

**Comment by misteroneill** [comment]
It's also annoying that it runs when you are doing another kind of push, like deleting a branch (`git push origin :foo`) or pushing tags (`git push --tags`); so, this should be really helpful!

**Comment by BrandonOCasey** [comment]
This is going to be done upstream in the generator: https://github.com/videojs/generator-videojs-plugin/pull/218
