### ISSUE TITLE
Script to set up Git pre-commit hook

### ISSUE THREAD

**Issue by misteroneill** [videojs/standard#3]
It'd be nice to provide a script to set up a Git pre-commit hook for users to test their JS code before they're allowed to commit.

**Comment by dmlap** [comment]
Sometimes it's handy to commit work-in-progress stuff locally and it would frustrate me if that got blocked. Is it possible to make it optional?

**Comment by gkatsev** [comment]
We can provide a script. Users would need to install it by default.

**Comment by misteroneill** [comment]
@dmlap That makes sense and, as @gkatsev said, I think users would have to run the script to set up their pre-commit hook.

Alternatively, [there is documentation on how to create one that runs `vjsstandard` before committing](https://github.com/videojs/standard#is-there-a-git-pre-commit-hook-for-vjsstandard).

What _won't_ be optional is for `npm test` to pass if linting fails.

**Comment by dmlap** [comment]
Makes sense. Thanks for the clarification!

**Comment by gkatsev** [comment]
Also, consider integrating it with [githooks](https://www.npmjs.com/package/githooks)

**Comment by misteroneill** [comment]
This is happening elsewhere.
