### ISSUE TITLE
Make function declarations acceptable

### ISSUE THREAD

**Issue by misteroneill** [videojs/standard#6]
Currently, the linter will error out on function declarations:

```js
function foo() {}
```

and function expressions are acceptable:

```js
const foo = function() {};
```

However, Babel will transform these into this form:

```js
var foo = function foo() {};
```

This would be fine except there is an issue in IE8 where if you reference `foo` within the body of the function, it will refer to a different value than the expected function object!

As such, we should make function declarations acceptable - either by turning them into warnings or removing the limitation entirely. I propose the latter as declarations are perfectly fine.

**Comment by gkatsev** [comment]
Also, we should take a look at whether babel 6 has this issue or whether it's configurable there because that's the actual solution to the problem.

**Comment by misteroneill** [comment]
Yeah, we should definitely investigate whether or not Babel 6 creates named function expressions.
